// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1nXkBCvkriBna1khoWQz_JxfNb794NpM',
    appId: '1:575974943870:web:470ce703d47392208e3c2f',
    messagingSenderId: '575974943870',
    projectId: 'ff-kit',
    authDomain: 'ff-kit.firebaseapp.com',
    storageBucket: 'ff-kit.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRU89MM99PM1SHyooDUUxj-F2fHz6rggM',
    appId: '1:575974943870:android:0a3cd7cebe67e0398e3c2f',
    messagingSenderId: '575974943870',
    projectId: 'ff-kit',
    storageBucket: 'ff-kit.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCT5QclXtOTZQG00LXXCBoBXJeIUKe3p2o',
    appId: '1:575974943870:ios:fee7b78e909f25528e3c2f',
    messagingSenderId: '575974943870',
    projectId: 'ff-kit',
    storageBucket: 'ff-kit.firebasestorage.app',
    iosBundleId: 'fr.benoitfontaine.starter.recette',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCT5QclXtOTZQG00LXXCBoBXJeIUKe3p2o',
    appId: '1:575974943870:ios:7d87f82d470fc9368e3c2f',
    messagingSenderId: '575974943870',
    projectId: 'ff-kit',
    storageBucket: 'ff-kit.firebasestorage.app',
    iosBundleId: 'pro.listo.flutterStarterKit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1nXkBCvkriBna1khoWQz_JxfNb794NpM',
    appId: '1:575974943870:web:261266ae01ca1e0a8e3c2f',
    messagingSenderId: '575974943870',
    projectId: 'ff-kit',
    authDomain: 'ff-kit.firebaseapp.com',
    storageBucket: 'ff-kit.firebasestorage.app',
  );
}
